#!/usr/bin/env python3

from __future__ import annotations
 
import argparse
import csv
import os
import shutil
from typing import List
 
SOIL = "0.42 0.32 0.22"
SOIL_SPEC = "0.05 0.05 0.05"
LEAF = "0.20 0.45 0.12"
LEAF_LIGHT = "0.34 0.62 0.20"
WEED = "0.75 0.72 0.15"
 
 
def load_lanes(path: str) -> List[dict]:
    with open(path, newline="") as f:
        return [{"y": float(r["y"]), "x_min": float(r["x_min"]),
                 "x_max": float(r["x_max"])} for r in csv.DictReader(f)]
 
 
def load_weeds(path: str) -> List[dict]:
    with open(path, newline="") as f:
        return [{"x": float(r["x"]), "y": float(r["y"]),
                 "r": float(r["radius"])} for r in csv.DictReader(f)]
 
 
def clump(name: str, x: float, y: float, size: float, h: float,
          colour: str) -> str:
    """One plant clump: two crossed boxes read as foliage from any angle."""
    return f"""      <link name="{name}">
        <pose>{x:.3f} {y:.3f} {h/2:.3f} 0 0 0</pose>
        <visual name="a">
          <geometry><box><size>{size:.3f} {size:.3f} {h:.3f}</size></box></geometry>
          <material>
            <ambient>{colour} 1</ambient>
            <diffuse>{colour} 1</diffuse>
            <specular>0.02 0.02 0.02 1</specular>
          </material>
        </visual>
        <visual name="b">
          <pose>0 0 0 0 0 0.785</pose>
          <geometry><box><size>{size*0.8:.3f} {size*0.8:.3f} {h*0.75:.3f}</size></box></geometry>
          <material>
            <ambient>{LEAF_LIGHT} 1</ambient>
            <diffuse>{LEAF_LIGHT} 1</diffuse>
          </material>
        </visual>
      </link>
"""
 
 
def build(args) -> None:
    lanes = load_lanes(os.path.join(args.world_dir, f"lanes_{args.seed}.csv"))
    weeds = load_weeds(
        os.path.join(args.world_dir, f"ground_truth_{args.seed}.csv"))
 
    lane_ys = sorted(ln["y"] for ln in lanes)
    spacing = lane_ys[1] - lane_ys[0]
    row_ys = [y + spacing / 2.0 for y in lane_ys[:-1]]
    x_min, x_max = lanes[0]["x_min"], lanes[0]["x_max"]
 
    # Ground sized to the field plus a working margin, not the 50x27.5 m slab
    # the experiment world uses. A plane far larger than the crop makes the
    # field look like a postage stamp in every screenshot.
    pad = 3.0
    gx = (x_max - x_min) + 2 * pad
    gy = (max(lane_ys) - min(lane_ys)) + 2 * pad
    cx = (x_min + x_max) / 2.0
    cy = (min(lane_ys) + max(lane_ys)) / 2.0
 
    parts = [f"""<?xml version="1.0" ?>
<!-- GENERATED by make_demo_world.py from seed {args.seed}. Presentation only:
     real time is throttled, so a full mission would take hours. Run
     experiments against the seed-{args.seed} world instead. -->
<sdf version="1.9">
  <world name="agri_field">
 
    <physics name="watchable" type="dart">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
 
    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
 
    <gravity>0 0 -9.81</gravity>
 
    <scene>
      <ambient>0.55 0.56 0.58 1</ambient>
      <background>0.72 0.80 0.89 1</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>
 
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 12 0 0 0</pose>
      <diffuse>0.95 0.92 0.85 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.35 -0.8</direction>
    </light>
    <!-- Fill light, no shadows: keeps the far side of each robot readable. -->
    <light type="directional" name="fill">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.28 0.30 0.34 1</diffuse>
      <direction>0.6 -0.4 -0.7</direction>
    </light>
 
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <pose>{cx:.3f} {cy:.3f} 0 0 0 0</pose>
          <geometry><box><size>{gx:.2f} {gy:.2f} 0.02</size></box></geometry>
          <surface><friction><ode>
            <mu>1.0</mu><mu2>1.0</mu2>
          </ode></friction></surface>
        </collision>
        <visual name="v">
          <pose>{cx:.3f} {cy:.3f} 0 0 0 0</pose>
          <geometry><box><size>{gx:.2f} {gy:.2f} 0.02</size></box></geometry>
          <material>
            <ambient>{SOIL} 1</ambient>
            <diffuse>{SOIL} 1</diffuse>
            <specular>{SOIL_SPEC} 1</specular>
          </material>
        </visual>
      </link>
    </model>
"""]
 
    # Crop rows. Clumps rather than one long strip: a solid box reads as a
    # painted line, a row of clumps reads as a crop. Purely visual — no
    # collision, so a robot that clipped a row would not be stopped by it and
    # the clearance claim still has to be checked from the pose log.
    parts.append('    <model name="crop_field">\n      <static>true</static>\n')
    k = 0
    for ry in row_ys:
        x = x_min
        while x <= x_max:
            parts.append(clump(f"crop_{k}", x, ry, args.plant_size,
                               args.plant_height, LEAF))
            k += 1
            x += args.plant_spacing
    parts.append("    </model>\n")
 
    parts.append('    <model name="weeds">\n      <static>true</static>\n')
    for i, w in enumerate(weeds):
        r = max(w["r"], 0.10)
        parts.append(f"""      <link name="weed_{i}">
        <pose>{w['x']:.3f} {w['y']:.3f} {r:.3f} 0 0 0</pose>
        <visual name="v">
          <geometry><sphere><radius>{r:.3f}</radius></sphere></geometry>
          <material>
            <ambient>{WEED} 1</ambient>
            <diffuse>{WEED} 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
      </link>
""")
    parts.append("    </model>\n\n  </world>\n</sdf>\n")
 
    out_sdf = os.path.join(args.world_dir, f"agri_field_{args.demo_seed}.sdf")
    with open(out_sdf, "w") as f:
        f.write("".join(parts))
 
    for stem in ("lanes", "ground_truth"):
        shutil.copy(
            os.path.join(args.world_dir, f"{stem}_{args.seed}.csv"),
            os.path.join(args.world_dir, f"{stem}_{args.demo_seed}.csv"))
 
    print(f"wrote {out_sdf}")
    print(f"  {k} crop clumps, {len(weeds)} weeds, "
          f"ground {gx:.1f} x {gy:.1f} m")
    print(f"  launch with seed:={args.demo_seed} headless:=false")
 
 
def main():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--seed", type=int, default=0,
                   help="Experiment seed to copy the geometry from.")
    p.add_argument("--demo-seed", type=int, default=99, dest="demo_seed",
                   help="Seed number the demo world is written under.")
    p.add_argument("--world-dir", default=os.path.expanduser("~/agri-worlds"),
                   dest="world_dir")
    p.add_argument("--plant-spacing", type=float, default=0.55,
                   dest="plant_spacing",
                   help="Metres between crop clumps along a row. Lower looks "
                        "denser and renders slower.")
    p.add_argument("--plant-size", type=float, default=0.20,
                   dest="plant_size")
    p.add_argument("--plant-height", type=float, default=0.30,
                   dest="plant_height")
    build(p.parse_args())
 
 
if __name__ == "__main__":
    main()
