#!/usr/bin/env python3
import argparse
import csv
import math
import os
import random


def build_field(cfg, rng):
    """Return (rows, weeds). Pure function of rng state."""
    rows = []
    for i in range(cfg.n_rows):
        y = i * cfg.row_spacing
        rows.append({"index": i, "y": y})

    # Drivable lanes sit between rows, plus one on each outside edge.
    lanes = [-cfg.row_spacing / 2.0]
    lanes += [r["y"] + cfg.row_spacing / 2.0 for r in rows]

    field_area = cfg.row_length * (cfg.n_rows * cfg.row_spacing)
    n_weeds = max(1, int(round(field_area * cfg.weed_density)))

    weeds = []
    for wid in range(n_weeds):
        x = rng.uniform(cfg.headland, cfg.row_length - cfg.headland)
        if rng.random() < cfg.intra_row_fraction:
            # Intra-row: nestled against the crop. These are the hard ones and
            # the entire premise of the project -- keep the fraction high.
            row = rng.choice(rows)
            y = row["y"] + rng.uniform(-1.0, 1.0) * (cfg.crop_row_width / 2.0)
            in_row = 1
        else:
            lane = rng.choice(lanes)
            y = lane + rng.gauss(0.0, cfg.row_spacing * 0.12)
            in_row = 0
        radius = rng.uniform(cfg.weed_radius_min, cfg.weed_radius_max)
        weeds.append({"id": wid, "x": x, "y": y, "radius": radius,
                      "in_row": in_row})

    return rows, lanes, weeds


CROP_ROW_LINK = """
      <link name="crop_row_{i}">
        <pose>{cx} {cy} {hz} 0 0 0</pose>
        <collision name="c">
          <geometry><box><size>{length} {width} {height}</size></box></geometry>
        </collision>
        <visual name="v">
          <geometry><box><size>{length} {width} {height}</size></box></geometry>
          <material>
            <ambient>0.10 0.32 0.08 1</ambient>
            <diffuse>0.14 0.45 0.11 1</diffuse>
          </material>
        </visual>
      </link>"""

WEED_LINK = """
      <link name="weed_{id}">
        <pose>{x} {y} 0.03 0 0 0</pose>
        <visual name="v">
          <geometry><sphere><radius>{radius}</radius></sphere></geometry>
          <material>
            <ambient>0.55 0.50 0.05 1</ambient>
            <diffuse>0.85 0.78 0.08 1</diffuse>
          </material>
        </visual>
      </link>"""


def emit_sdf(cfg, rows, weeds):
    field_w = cfg.n_rows * cfg.row_spacing

    crop_links = "".join(
        CROP_ROW_LINK.format(
            i=r["index"],
            cx=cfg.row_length / 2.0,
            cy=r["y"],
            hz=cfg.crop_height / 2.0,
            length=cfg.row_length,
            width=cfg.crop_row_width,
            height=cfg.crop_height,
        )
        for r in rows
    )

    weed_links = "".join(
        WEED_LINK.format(id=w["id"], x=w["x"], y=w["y"], radius=w["radius"])
        for w in weeds
    )

    return f"""<?xml version="1.0" ?>
<!-- GENERATED by generate_field.py  seed={cfg.seed}  DO NOT EDIT BY HAND -->
<sdf version="1.9">
  <world name="agri_field">

    <physics name="fast" type="dart">
      <max_step_size>{cfg.step_size}</max_step_size>
      <!-- 0 = run unthrottled. Set to 1.0 only when you want to watch it. -->
      <real_time_factor>{cfg.rtf}</real_time_factor>
    </physics>

    <!-- NOTE: gz-sim-sensors-system is deliberately absent. No rendering. -->
    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>

    <gravity>0 0 -9.81</gravity>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <direction>-0.4 0.2 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <geometry><plane><normal>0 0 1</normal>
            <size>{cfg.row_length + 20} {field_w + 20}</size></plane></geometry>
          <surface><friction><ode>
            <mu>1.0</mu><mu2>1.0</mu2>
          </ode></friction></surface>
        </collision>
        <visual name="v">
          <geometry><plane><normal>0 0 1</normal>
            <size>{cfg.row_length + 20} {field_w + 20}</size></plane></geometry>
          <material>
            <ambient>0.28 0.20 0.13 1</ambient>
            <diffuse>0.38 0.27 0.18 1</diffuse>
          </material>
        </visual>
      </link>
    </model>

    <model name="crop_field">
      <static>true</static>{crop_links}
    </model>

    <!-- Visual only. Treatment is a geometric predicate in the sim, not a
         physical interaction, so these need no collision or inertia. -->
    <model name="weeds">
      <static>true</static>{weed_links}
    </model>

  </world>
</sdf>
"""



def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--out", default="worlds")

    p.add_argument("--n-rows", type=int, default=10)
    p.add_argument("--row-length", type=float, default=30.0)
    p.add_argument("--row-spacing", type=float, default=0.75)
    p.add_argument("--crop-row-width", type=float, default=0.22)
    p.add_argument("--crop-height", type=float, default=0.35)
    p.add_argument("--headland", type=float, default=1.5,
                   help="Keep-out margin at each end of a row [m].")

    p.add_argument("--weed-density", type=float, default=0.35,
                   help="Weeds per square metre of field.")
    p.add_argument("--weed-radius-min", type=float, default=0.05)
    p.add_argument("--weed-radius-max", type=float, default=0.14)
    p.add_argument("--intra-row-fraction", type=float, default=0.7,
                   help="Fraction of weeds inside the crop row.")

    p.add_argument("--step-size", type=float, default=0.004)
    p.add_argument("--rtf", type=float, default=0.0,
                   help="0 = unthrottled (batch runs). 1.0 = wall-clock.")

    cfg = p.parse_args()
    rng = random.Random(cfg.seed)

    rows, lanes, weeds = build_field(cfg, rng)
    os.makedirs(cfg.out, exist_ok=True)

    sdf_path = os.path.join(cfg.out, f"agri_field_{cfg.seed}.sdf")
    with open(sdf_path, "w") as f:
        f.write(emit_sdf(cfg, rows, weeds))

    csv_path = os.path.join(cfg.out, f"ground_truth_{cfg.seed}.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "x", "y", "radius", "in_row"])
        for wd in weeds:
            w.writerow([wd["id"], round(wd["x"], 4), round(wd["y"], 4),
                        round(wd["radius"], 4), wd["in_row"]])

    lane_path = os.path.join(cfg.out, f"lanes_{cfg.seed}.csv")
    with open(lane_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["lane_index", "y", "x_min", "x_max"])
        for i, y in enumerate(lanes):
            w.writerow([i, round(y, 4), 0.0, round(cfg.row_length, 4)])

    intra = sum(w["in_row"] for w in weeds)
    print(f"seed={cfg.seed}  weeds={len(weeds)} "
          f"(intra-row {intra}, inter-row {len(weeds) - intra})  "
          f"lanes={len(lanes)}")
    print(f"  {sdf_path}\n  {csv_path}\n  {lane_path}")


if __name__ == "__main__":
    main()
